[package]
name = "truth-table"
version = "0.0.0"
authors = ["Caleb Smith <karagenit@outlook.com>"]

[lib]
name = "libtruth"
path = "src/lib-truth.rs"

[[bin]]
name = "truth-table"
path = "src/main.rs"

[dependencies]
